apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
spec:
  ports:
    - name: namenode
      protocol: TCP
      port: 8020
      targetPort: 8020
  clusterIP: None
  selector:
    app: hadoop-namenode
