apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9000
          env:
            - name: CLUSTER_NAME
              value: "hadoop-cluster"
          volumeMounts:
            - name: namenode-storage
              mountPath: /hadoop/dfs/name
      volumes:
        - name: namenode-storage
          persistentVolumeClaim:
            claimName: namenode-pvc
